### ISSUE TITLE
RuntimeException when trying to use FabSpeedDialBehaviour

### ISSUE THREAD

**Issue by scottyab** [yavski/fab-speed-dial#29]
Great library btw thanks. However I'm seeing an issue using the FabSpeedDialBehaviour which I was hoping to use to hide the FAB when scrolling a recyclerview. 

Using version `fab-speed-dial:1.0.4`

Min SDK 21, 
Target 24,  
buildToolsVersion "23.0.3"
Dependancies 
compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha4'
compile 'com.android.support:design:24.2.0'
compile 'com.android.support:multidex:1.0.1'
compile 'com.android.support:recyclerview-v7:24.2.0'

```
Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass io.github.yavski.fabspeeddial.FabSpeedDialBehaviour
...
 Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
                      at java.lang.Class.getConstructor(Class.java:531)
                      at java.lang.Class.getConstructor(Class.java:495)
                      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:595)
```

This is my xml

```
  <io.github.yavski.fabspeeddial.FabSpeedDial
        android:id="@+id/addFab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        app:fabGravity="bottom_end"
        app:fabMenu="@menu/timeline_fab_menu"
        app:layout_behavior="io.github.yavski.fabspeeddial.FabSpeedDialBehaviour"
        app:miniFabBackgroundTint="@android:color/white"
        app:miniFabDrawableTint="?attr/colorPrimaryDark"
        app:miniFabTitleTextColor="?attr/colorPrimaryDark" />

```

**Comment by scottyab** [comment]
Digging deeper it seems the `FabSpeedDialBehaviour` needs this constructor adding

```
  public FabSpeedDialBehaviour(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
```

**Comment by yavski** [comment]
Sorry for taking ages to respond, I've added the constructor in 1.0.5. Let me know if you still have that issue.
