### ISSUE TITLE
Error inflating class io.github.yavski.fabspeeddial.FabSpeedDial

### ISSUE THREAD

**Issue by Acorde** [yavski/fab-speed-dial#42]
Hi, Below is the XML:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity"
    >

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:padding="16dp">

        <io.github.yavski.fabspeeddial.FabSpeedDial
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            app:fabGravity="bottom_end"
            app:fabMenu="@menu/menu_main"
            app:miniFabBackgroundTint="@android:color/white"
            app:miniFabDrawableTint="?attr/colorPrimaryDark"
            app:miniFabTitleTextColor="?attr/colorPrimaryDark" />

    </FrameLayout>

</RelativeLayout>
```

**Comment by sunnyshrestha** [comment]
Hello Acorde. I was having the same issue until I realised that I had defined the wrong menu resource file. Please check if you are having a similar issue.

**Comment by yavski** [comment]
@Acorde has this been resolved now? If not, please provide your stack trace.

**Comment by prashanthd** [comment]
Below is the exception I got

 android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class io.github.yavski.fabspeeddial.FabSpeedDial
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                        at com.company.qbucks.fragments.Home_fragment.onCreateView(Home_fragment.java:72)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
                                                                        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                                                                        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1085)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                        at android.view.View.measure(View.java:18809)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                        at android.os.Handler.handleCallback(Handler.java:746)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                    	at java.lang.reflect.Method.invoke(Native

**Comment by prashanthd** [comment]
this is menu file

<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <item
        android:id="@+id/languagesFilter"
        android:icon="@drawable/language"
        android:title="Languages" />
    <item
        android:id="@+id/pointsFilter"
        android:icon="@drawable/points"
        android:title="Points"/>
    <item
        android:id="@+id/channnelsFilter"
        android:icon="@drawable/remote"
        android:title="Channels" />

    <item
        android:id="@+id/campaignFilter"
        android:icon="@drawable/receive"
        android:title="Campaign Type" />


    
    <item
        android:id="@+id/removeFliter"
        android:icon="@drawable/filter"
        android:title="Clear Filters" />
</menu>

**Comment by leonardo2204** [comment]
@prashanthd Sometimes commenting on xml gives bizarre errors.
Try deleting the dateFilter row and check if it works.

**Comment by SergiyBojko** [comment]
I managed to fix this problem by adding Android Design Support Library to my project.

**Comment by FrozenHeavenFire** [comment]
I have the same issue in android 4.4 , and throw InvocationTargetException.

**Comment by penn5** [comment]
If this is resolved, why isn't it closed?

**Comment by karique01** [comment]
adding the implementation 'com.android.support:design:26.1.0' dependency worked for me

**Comment by sayyadsuleman** [comment]
Look your layout for this namespace
xmlns:app="http://schemas.android.com/apk/res-auto"
If not just copy and paste it
